var namespace_o_r_m_1_1_exceptions =
[
    [ "ControllerDoesNotExistException", "class_o_r_m_1_1_exceptions_1_1_controller_does_not_exist_exception.html", null ],
    [ "ControllerNamespaceUnknownException", "class_o_r_m_1_1_exceptions_1_1_controller_namespace_unknown_exception.html", null ],
    [ "FieldDoesNotExistException", "class_o_r_m_1_1_exceptions_1_1_field_does_not_exist_exception.html", null ],
    [ "IncludePathDoesNotExistException", "class_o_r_m_1_1_exceptions_1_1_include_path_does_not_exist_exception.html", null ],
    [ "IncludePathIsNotADirectoryException", "class_o_r_m_1_1_exceptions_1_1_include_path_is_not_a_directory_exception.html", null ],
    [ "IncorrectSessionLockIndexException", "class_o_r_m_1_1_exceptions_1_1_incorrect_session_lock_index_exception.html", null ],
    [ "InvalidActionException", "class_o_r_m_1_1_exceptions_1_1_invalid_action_exception.html", null ],
    [ "ORMConfigurationException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_configuration_exception.html", null ],
    [ "ORMException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_exception.html", null ],
    [ "ORMFetchException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_fetch_exception.html", null ],
    [ "ORMFetchIntoClassNotFoundException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_fetch_into_class_not_found_exception.html", null ],
    [ "ORMFetchIntoException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_fetch_into_exception.html", null ],
    [ "ORMFetchIntoRelatedClassNotFoundException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_fetch_into_related_class_not_found_exception.html", null ],
    [ "ORMFindByInvalidFieldException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_find_by_invalid_field_exception.html", null ],
    [ "ORMInsertException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_insert_exception.html", null ],
    [ "ORMInvalidStaticMethodException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_invalid_static_method_exception.html", null ],
    [ "ORMPDOException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_p_d_o_exception.html", null ],
    [ "ORMPDOInvalidDatabaseConfigurationException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_p_d_o_invalid_database_configuration_exception.html", null ],
    [ "ORMUpdateException", "class_o_r_m_1_1_exceptions_1_1_o_r_m_update_exception.html", null ],
    [ "PHPErrorException", "class_o_r_m_1_1_exceptions_1_1_p_h_p_error_exception.html", null ],
    [ "PHPErrorNoticeException", "class_o_r_m_1_1_exceptions_1_1_p_h_p_error_notice_exception.html", null ],
    [ "PHPErrorWarningException", "class_o_r_m_1_1_exceptions_1_1_p_h_p_error_warning_exception.html", null ],
    [ "PHPFatalErrorException", "class_o_r_m_1_1_exceptions_1_1_p_h_p_fatal_error_exception.html", null ]
];